import unittest
import moepkg/[editorstatus, gapbuffer, bufferstatus, unicodeext]

include moepkg/configmode

const correctBuffer = @[
  ru"Standard",
  ru"  theme                         dark",
  ru"  number                        true",
  ru"  currentNumber                 true",
  ru"  cursorLine                    false",
  ru"  statusBar                     true",
  ru"  tabLine                       true",
  ru"  syntax                        true",
  ru"  indentationLines              true",
  ru"  tabStop                       2",
  ru"  autoCloseParen                true",
  ru"  autoIndent                    true",
  ru"  disableChangeCursor           false",
  ru"  defaultCursor                 blinkBlock",
  ru"  normalModeCursor              blinkBlock",
  ru"  insertModeCursor              blinkIbeam",
  ru"  autoSave                      false",
  ru"  autoSaveInterval              5",
  ru"  liveReloadOfConf              false",
  ru"  incrementalSearch             true",
  ru"  popUpWindowInExmode           true",
  ru"  replaceTextHighlight          true",
  ru"  highlightPairOfParen          true",
  ru"  autoDeleteParen               true",
  ru"  systemClipboard               true",
  ru"  highlightFullWidthSpace       true",
  ru"  highlightTrailingSpaces       true",
  ru"  highlightCurrentWord          true",
  ru"",
  ru"BuildOnSave",
  ru"  enable                        false",
  ru"  workspaceRoot                 ",
  ru"  command                       ",
  ru"",
  ru"TabLine",
  ru"  allBuffer                     false",
  ru"",
  ru"StatusBar",
  ru"  mode                          true",
  ru"  filename                      true",
  ru"  chanedMark                    true",
  ru"  line                          true",
  ru"  column                        true",
  ru"  encoding                      true",
  ru"  language                      true",
  ru"  directory                     true",
  ru"  multipleStatusBar             true",
  ru"  gitbranchName                 true",
  ru"  showGitInactive               false",
  ru"  showModeInactive              false",
  ru"",
  ru"WorkSpace",
  ru"  workSpaceLine                 false",
  ru"",
  ru"Highlight",
  ru"  reservedWord",
  ru"                                TODO",
  ru"                                WIP",
  ru"                                NOTE",
  ru"",
  ru"AutoBackup",
  ru"  enable                        true",
  ru"  idolTime                      10",
  ru"  interval                      5",
  ru"  backupDir                     ",
  ru"  dirToExclude                  /etc",
  ru"",
  ru"QuickRun",
  ru"  saveBufferWhenQuickRun        true",
  ru"  command                       ",
  ru"  timeout                       30",
  ru"  nimAdvancedCommand            c",
  ru"  ClangOptions                  ",
  ru"  CppOptions                    ",
  ru"  NimOptions                    ",
  ru"  shOptions                     ",
  ru"  bashOptions                   ",
  ru"",
  ru"Notification",
  ru"  screenNotifications           true",
  ru"  logNotifications              true",
  ru"  autoBackupScreenNotify        true",
  ru"  autoBackupLogNotify           true",
  ru"  autoSaveScreenNotify          true",
  ru"  autoSaveLogNotify             true",
  ru"  yankScreenNotify              true",
  ru"  yankLogNotify                 true",
  ru"  deleteScreenNotify            true",
  ru"  deleteLogNotify               true",
  ru"  saveScreenNotify              true",
  ru"  saveLogNotify                 true",
  ru"  workspaceScreenNotify         true",
  ru"  workspaceLogNotify            true",
  ru"  quickRunScreenNotify          true",
  ru"  quickRunLogNotify             true",
  ru"  buildOnSaveScreenNotify       true",
  ru"  buildOnSaveLogNotify          true",
  ru"  filerScreenNotify             true",
  ru"  filerLogNotify                true",
  ru"  restoreScreenNotify           true",
  ru"  restoreLogNotify              true",
  ru"",
  ru"Filer",
  ru"  showIcons                     true",
  ru"",
  ru"Theme",
  ru"  editorBg                      default",
  ru"  lineNum                       gray54  default",
  ru"  currentLineNum                teal    default",
  ru"  statusBarNormalMode           white   blue",
  ru"  statusBarModeNormalMode       black   white",
  ru"  statusBarNormalModeInactive   blue    white",
  ru"  statusBarInsertMode           white   blue",
  ru"  statusBarModeInsertMode       black   white",
  ru"  statusBarInsertModeInactive   blue    white",
  ru"  statusBarVisualMode           white   blue",
  ru"  statusBarModeVisualMode       black   white",
  ru"  statusBarVisualModeInactive   blue    white",
  ru"  statusBarReplaceMode          white   blue",
  ru"  statusBarModeReplaceMode      black   white",
  ru"  statusBarReplaceModeInactive  blue    white",
  ru"  statusBarFilerMode            white   blue",
  ru"  statusBarModeFilerMode        black   white",
  ru"  statusBarFilerModeInactive    blue    white",
  ru"  statusBarExMode               white   blue",
  ru"  statusBarModeExMode           black   white",
  ru"  statusBarExModeInactive       blue    white",
  ru"  statusBarGitBranch            white   blue",
  ru"  tab                           white   default",
  ru"  currentTab                    white   blue",
  ru"  commandBar                    gray100 default",
  ru"  errorMessage                  red     default",
  ru"  searchResult                  default red",
  ru"  visualMode                    gray100 purple_1",
  ru"  defaultChar                   gray100 default",
  ru"  currentFile                   gray100 teal",
  ru"  file                          gray100 default",
  ru"  dir                           blue    default",
  ru"  pcLink                        teal    default",
  ru"  popUpWindow                   gray100 black",
  ru"  popUpWinCurrentLine           blue    black",
  ru"  replaceText                   default red",
  ru"  parenText                     default white",
  ru"  currentWord                   default white",
  ru"  highlightFullWidthSpace       default white",
  ru"  highlightTrailingSpaces       red     red",
  ru"  workSpaceBar                  white   blue",
  ru"  reservedWord                  white   gray",
  ru"  currentSetting                gray100 teal",
]

suite "Config mode: Start configuration mode":
  test "Check buffer":
    var status = initEditorStatus()
    status.addNewBuffer(Mode.config)

    status.bufStatus[0].buffer = initConfigModeBuffer(status.settings)
    let buffer = status.bufStatus[0].buffer

    check buffer.len == correctBuffer.len

    for i in 0 ..< correctBuffer.len:
      check buffer[i] == correctBuffer[i]
