[Colors]

foreground = "#f8f5e3"
background = "#000000"

lineNum = "#8a8a8a"
lineNumBg = "#000000"

currentLineNum = "#008080"
currentLineNumBg = "#000000"

statusLineNormalMode = "#ffffff"
statusLineNormalModeBg = "#09aefa"
statusLineNormalModeLabel = "#000000"
statusLineNormalModeLabelBg = "#ffffff"
statusLineNormalModeInactive = "#09aefa"
statusLineNormalModeInactiveBg = "#ffffff"

statusLineInsertMode = "#ffffff"
statusLineInsertModeBg = "#09aefa"
statusLineInsertModeLabel = "#000000"
statusLineInsertModeLabelBg = "#ffffff"
statusLineInsertModeInactive = "#09aefa"
statusLineInsertModeInactiveBg = "#ffffff"

statusLineVisualMode = "#ffffff"
statusLineVisualModeBg = "#09aefa"
statusLineVisualModeLabel = "#000000"
statusLineVisualModeLabelBg = "#ffffff"
statusLineVisualModeInactive = "#09aefa"
statusLineVisualModeInactiveBg = "#ffffff"

statusLineReplaceMode = "#ffffff"
statusLineReplaceModeBg = "#09aefa"
statusLineReplaceModeLabel = "#000000"
statusLineReplaceModeLabelBg = "#ffffff"
statusLineReplaceModeInactive = "#09aefa"
statusLineReplaceModeInactiveBg = "#ffffff"

statusLineFilerMode = "#ffffff"
statusLineFilerModeBg = "#09aefa"
statusLineFilerModeLabel = "#000000"
statusLineFilerModeLabelBg = "#ffffff"
statusLineFilerModeInactive = "#09aefa"
statusLineFilerModeInactiveBg = "#ffffff"

statusLineExMode = "#ffffff"
statusLineExModeBg = "#09aefa"
statusLineExModeLabel = "#000000"
statusLineExModeLabelBg = "#ffffff"
statusLineExModeInactive = "#09aefa"
statusLineExModeInactiveBg = "#ffffff"

statusLineGitChangedLines = "#ffffff"
statusLineGitChangedLinesBg = "#0040ff"
statusLineGitBranch = "#ffffff"
statusLineGitBranchBg = "#0040ff"

tab = "#ffffff"
tabBg = "#000000"
currentTab = "#ffffff"
currentTabBg = "#09aefa"

commandLine = "#ffffff"
commandLineBg = "#000000"

errorMessage = "#ff0000"
errorMessageBg = "#000000"

warnMessage = "#ffff00"
warnMessageBg = "#000000"

searchResult = "#ffffff"
searchResultBg = "#ff0000"

selectArea = "#ffffff"
selectAreaBg = "#800080"

keyword = "#87d7ff"
functionName = "#00b7ce"
typeName = "#00ffff"
boolean = "#add8e6"
charLit = "#add8e6"
stringLit = "#add8e6"
specialVar = "#0090a8"
builtin = "#add8e6"
binNumber = "#add8e6"
decNumber = "#add8e6"
floatNumber = "#add8e6"
hexNumber = "#add8e6"
octNumber = "#add8e6"
comment = "#808080"
longComment = "#808080"
whitespace = "#808080"
preprocessor = "#0090a8"
pragma = "#0090a8"
identifier = "#f8f5e3"
table = "#0090a8"
date = "#0090a8"
operator = "#00b7ce"

enumMember = "#add8e6"
interfaceName = "#00b7ce"
typeParameter = "#add8e6"
parameter = "#add8e6"
variable = "#f8f5e3"
property = "#00b7ce"
string = "#add8e6"
event = "#f8f5e3"
function = "#00b7ce"
method = "#00b7ce"
macro = "#00b7ce"
regexp = "#add8e6"
decorator = "#add8e6"
angle = "#f8f5e3"
arithmetic = "#f8f5e3"
attribute = "#00b7ce"
attributeBracket = "#00b7ce"
bitwise = "#f8f5e3"
brace = "#f8f5e3"
bracket = "#f8f5e3"
builtinAttribute = "#00b7ce"
builtinType = "#00ffff"
colon = "#f8f5e3"
comma = "#f8f5e3"
comparison = "#f8f5e3"
constParameter = "#0090a8"
derive = "#00b7ce"
deriveHelper = "#00b7ce"
dot = "#f8f5e3"
escapeSequence = "#f8f5e3"
invalidEscapeSequence = "#ff0000"
formatSpecifier = "#f8f5e3"
generic = "#f8f5e3"
label = "#f8f5e3"
lifetime = "#0090a8"
logical = "#f8f5e3"
macroBang = "#f8f5e3"
parenthesis = "#f8f5e3"
punctuation = "#f8f5e3"
selfKeyword = "#f8f5e3"
selfTypeKeyword = "#f8f5e3"
semicolon = "#f8f5e3"
typeAlias = "#add8e6"
toolModule = "#f8f5e3"
union = "#00b7ce"
unresolvedReference = "#f8f5e3"

inlayHint = "#808080"
codeLens = "#808080"

currentFile = "#ffffff"
currentFileBg = "#09aefa"
file = "#ffffff"
fileBg = "#000000"
dir = "#09aefa"
dirBg = "#000000"
pcLink = "#008080"
pcLinkBg = "#000000"

popupWindow = "#ffffff"
popupWindowBg = "#000000"
popupWinCurrentLine = "#09aefa"
popupWinCurrentLineBg = "#000000"

replaceText = "#ffffff"
replaceTextBg = "#ff0000"

parenPair = "#ffffff"
parenPairBg = "#09aefa"

currentWord = "#ffffff"
currentWordBg = "#09aefa"

highlightFullWidthSpace = "#ff0000"

highlightTrailingSpaces = "#ff0000"

reservedWord = "#ffffff"
reservedWordBg = "#808080"

syntaxCheckInfo = "#ffff00"
syntaxCheckInfoBg = "#000000"
syntaxCheckHint = "#ffff00"
syntaxCheckHintBg = "#000000"
syntaxCheckWarn = "#ffff00"
syntaxCheckWarnBg = "#000000"
syntaxCheckErr = "#ff0000"
syntaxCheckErrBg = "#000000"

gitConflict = "#00ff00"
gitConflictBg = "#000000"

backupManagerCurrentLine = "#000000"
backupManagerCurrentLineBg = "#008080"

diffViewerAddedLine = "#008000"
diffViewerAddedLineBg = "#000000"
diffViewerDeletedLine = "#ff0000"
diffViewerDeletedLineBg = "#000000"

configModeCurrentLine = "#ffffff"
configModeCurrentLineBg = "#008080"

currentLineBg = "#444444"

foldingLine = "#808080"
foldingLineBg = "#3f3f3f"

sidebarGitAddedSign = "#008000"
sidebarGitAddedSignBg = "#000000"
sidebarGitDeletedSign = "#ff0000"
sidebarGitDeletedSignBg = "#000000"
sidebarGitChangedSign = "#ffff00"
sidebarGitChangedSignBg = "#000000"

sidebarSyntaxCheckInfoSign = "#ffff00"
sidebarSyntaxCheckInfoSignBg = "#000000"
sidebarSyntaxCheckHintSign = "#ffff00"
sidebarSyntaxCheckHintSignBg = "#000000"
sidebarSyntaxCheckWarnSign = "#ffff00"
sidebarSyntaxCheckWarnSignBg = "#000000"
sidebarSyntaxCheckErrSign = "#ff0000"
sidebarSyntaxCheckErrSignBg = "#000000"
