#[###################### GNU General Public License 3.0 ######################]#
#                                                                              #
#  Copyright (C) 2017─2026 Shuhei Nogawa                                       #
#                                                                              #
#  This program is free software: you can redistribute it and/or modify        #
#  it under the terms of the GNU General Public License as published by        #
#  the Free Software Foundation, either version 3 of the License, or           #
#  (at your option) any later version.                                         #
#                                                                              #
#  This program is distributed in the hope that it will be useful,             #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of              #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
#  GNU General Public License for more details.                                #
#                                                                              #
#  You should have received a copy of the GNU General Public License           #
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.      #
#                                                                              #
#[############################################################################]#

name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yaml'
      - 'moe.nimble'
      - 'nimble.lock'
      - 'src/**'
    branches:
      - develop
      - master
  pull_request:
    paths:
      - '.github/workflows/build.yaml'
      - 'moe.nimble'
      - 'nimble.lock'
      - 'src/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macOS-latest'
        nim-version:
          - '2.0.10'
          - 'stable'
          - 'devel'

    name: Build on ${{ matrix.nim-version }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v7

      - name: Cache nimble
        # TODO: Remove next line
        #  temporarily work around: https://github.com/orgs/community/discussions/180160
        if: runner.os != 'macOS'
        id: cache-nimble
        uses: actions/cache@v6
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-v2-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-v2-

      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.nim-version != 'devel'

      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim-version }}
          use-nightlies: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.nim-version == 'devel'

      - run: nimble build -y
