######################## GNU General Public License 3.0 ########################
##                                                                            ##
## Copyright (C) 2017─2023 Shuhei Nogawa                                      ##
##                                                                            ##
## This program is free software: you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation, either version 3 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program.  If not, see <https://www.gnu.org/licenses/>.     ##
##                                                                            ##
################################################################################

name: Integration tests

on:
  push:
    paths:
      - '.github/workflows/integration-test.yaml'
      - 'moe.nimble'
      - 'src/**'
      - 'shpec.sh'
    branches:
      - develop
      - master
  pull_request:
    paths:
      - '.github/workflows/integration-test.yaml'
      - 'moe.nimble'
      - 'src/**'
      - 'shpec.sh'

permissions:
  contents: read

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip job"

  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "Before job"

  test:
    name: build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: before
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macOS-latest
          # - windows-latest
    env:
      NIM_VERSION: stable
    steps:
    - uses: actions/checkout@v3.6.0
    - run: |
        sudo apt-get update -yqq
        sudo apt-get install -y gcc libncursesw5-dev build-essential
    - uses: jiro4989/setup-nim-action@v1.4.9
      with:
        nim-version: ${{ env.NIM_VERSION }}

    - name: Install integration tools
      run: |
        # shpec
        sudo sh -c "$(curl -L https://raw.githubusercontent.com/rylnd/shpec/master/install.sh)"
        # abduco
        wget https://github.com/martanne/abduco/releases/download/v0.6/abduco-0.6.tar.gz
        tar -zxvf abduco-0.6.tar.gz
        cd abduco-0.6
        make && sudo make install

    - name: Install moe
      run: nimble install --verbose -y

    - name: Run integration test
      run: shpec ./shpec.sh
