######################## GNU General Public License 3.0 ########################
##                                                                            ##
## Copyright (C) 2017─2023 fox0430                                            ##
##                                                                            ##
## This program is free software: you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation, either version 3 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program.  If not, see <https://www.gnu.org/licenses/>.     ##
##                                                                            ##
################################################################################

name: Scriv

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create:
    name: create
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.2

      - name: scriv
        uses: kevinmatthes/create-scriv-fragment@v0.2.3

      - name: push
        run: git push

################################################################################
